name: Update and (Re)Start Containers

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with: 
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to Remote Server
        env:
          REMOTE_USER: ${{ secrets.USERNAME }}
          REMOTE_HOST: ${{ secrets.HOST }}
        run: |
          ssh -o StrictHostKeyChecking=no $REMOTE_USER@$REMOTE_HOST << 'EOF'
            cd ./P3-public3
            git fetch --all
            git pull origin master
            docker-compose up -d
            sleep 60s
            docker-compose logs
            docker-compose down
          EOF


      # - name: Update Docker Image
      #   run: |
      #     docker pull blagotch/docker-frontend-backend-db-api:1.0
      #     docker pull blagotch/docker-frontend-backend-db-web:1.0
      #     docker pull mongo:4.4.6
      #     docker run --name api -d blagotch/docker-frontend-backend-db-api:1.0
      #     docker run --name web -d blagotch/docker-frontend-backend-db-web:1.0
      #     docker run --name mongo -d mongo:4.4.6
